id = "wds"
name = "Widget Designer Script"
version = "0.1.0"
schema_version = 1
description = "Widget Designer Script (.wds) language support"
repository = "https://github.com/auslinx73/zed-wds-extension"
authors = ["Andrey"]

[grammars.wds]
repository = "https://github.com/auslinx73/tree-sitter-wds"
rev = "e5eadab6233333e0af4575146aa03d02d979a0e9"
