id = "wds"
name = "Widget Designer Script"
version = "0.1.0"
schema_version = 1
description = "Widget Designer Script (.wds) language support"
repository = "https://github.com/auslinx73/zed-wds-extension"
authors = ["Andrey"]

[grammars.wds]
repository = "https://github.com/auslinx73/tree-sitter-wds"
rev = "021fab9bc0be981e36b3c23f9fa755e09b5c7707"
